version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: docker

  db:
    image: postgres
    volumes:
      - /root/psql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=php-docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
