version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./app/public:/var/www/html/public
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: docker

  db:
    image: postgres:12
    volumes:
      - /root/psql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=php-docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
